### ISSUE TITLE
Running independent of webserver

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#69]
Is a web server absolutely necessary?  Could this not be run as a standalone web service on a dedicated port?

**Comment by 16zzundel5** [comment]
No, I think that we could probably have an application server serve the static frontend. The problem is that I believe this is generally bad practice...or, I've always read that it is. Let me do some research on why/if that's true and get back to you. Right now, nginx is the webserver which handles static files and routes requests to the application server, which is uWSGI.

**Comment by cjmyers** [comment]
Its fine.  I was thinking for debugging.  This is what I’m doing with sbolstack/synbiohub.  We can discuss when we meet next week.
